apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-role-k8sevents
rules:
- apiGroups: [""]
  resources:
  - events
  - pods
  verbs: ["get", "list", "watch"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-k8sevents
  namespace: otel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-k8sevents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-role-k8sevents
subjects:
  - kind: ServiceAccount
    name: otel-k8sevents
    namespace: otel 
